# Prometheus configuration for Procur

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'procur'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

# Load alerting rules
rule_files:
  - "alerting_rules.yml"

# Scrape configurations
scrape_configs:
  # Procur API metrics
  - job_name: 'procur-api'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
  
  # Procur metrics endpoint
  - job_name: 'procur-metrics'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 10s
  
  # Celery workers
  - job_name: 'procur-workers'
    static_configs:
      - targets:
          - 'localhost:9091'  # negotiation worker
          - 'localhost:9092'  # enrichment worker
          - 'localhost:9093'  # contracts worker
          - 'localhost:9094'  # notifications worker
    scrape_interval: 10s
  
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 10s
  
  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 10s
  
  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 10s
