"""add_negotiation_events_table

Revision ID: b27d1932173a
Revises: 20251005_fix_offers
Create Date: 2025-10-06 23:53:06.589322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b27d1932173a'
down_revision: Union[str, None] = '20251005_fix_offers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_events_session_id'), 'negotiation_events', ['session_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('mfa_required', sa.Boolean(), nullable=False),
    sa.Column('mfa_success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('oauth_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('provider_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_connections_provider'), 'oauth_connections', ['provider'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('api_keys', sa.Column('hashed_secret', sa.String(length=255), nullable=False))
    op.add_column('api_keys', sa.Column('usage_count', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('api_keys_key_id_key'), 'api_keys', type_='unique')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_id'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_id'), 'api_keys', ['key_id'], unique=True)
    op.drop_column('api_keys', 'key_hash')
    op.add_column('audit_logs', sa.Column('actor_type', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('actor_id', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('negotiation_session_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('event_data', sa.JSON(), nullable=True))
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('audit_logs_log_id_key'), 'audit_logs', type_='unique')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'negotiation_sessions', ['negotiation_session_id'], ['id'])
    op.drop_column('audit_logs', 'log_metadata')
    op.drop_column('audit_logs', 'log_id')
    op.drop_column('audit_logs', 'timestamp')
    op.add_column('contracts', sa.Column('final_offer_id', sa.Integer(), nullable=True))
    op.add_column('contracts', sa.Column('unit_price', sa.Float(), nullable=False))
    op.add_column('contracts', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('contracts', sa.Column('term_months', sa.Integer(), nullable=False))
    op.add_column('contracts', sa.Column('payment_terms', sa.String(length=50), nullable=False))
    op.add_column('contracts', sa.Column('renewal_date', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('document_hash', sa.String(length=64), nullable=True))
    op.add_column('contracts', sa.Column('template_version', sa.String(length=50), nullable=True))
    op.add_column('contracts', sa.Column('signed_by_buyer', sa.Boolean(), nullable=False))
    op.add_column('contracts', sa.Column('signed_by_vendor', sa.Boolean(), nullable=False))
    op.add_column('contracts', sa.Column('buyer_signature_date', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('vendor_signature_date', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('docusign_envelope_id', sa.String(length=100), nullable=True))
    op.add_column('contracts', sa.Column('purchase_order_id', sa.String(length=100), nullable=True))
    op.add_column('contracts', sa.Column('erp_sync_status', sa.String(length=50), nullable=True))
    op.add_column('contracts', sa.Column('erp_synced_at', sa.DateTime(), nullable=True))
    op.add_column('contracts', sa.Column('value_adds', sa.JSON(), nullable=True))
    op.add_column('contracts', sa.Column('special_terms', sa.JSON(), nullable=True))
    op.alter_column('contracts', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contracts', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('contracts_contract_id_key'), 'contracts', type_='unique')
    op.drop_index(op.f('ix_contracts_contract_id'), table_name='contracts')
    op.create_index(op.f('ix_contracts_contract_id'), 'contracts', ['contract_id'], unique=True)
    op.drop_constraint(op.f('contracts_offer_id_fkey'), 'contracts', type_='foreignkey')
    op.drop_constraint(op.f('contracts_signed_by_fkey'), 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'offers', ['final_offer_id'], ['id'])
    op.drop_column('contracts', 'signed_at')
    op.drop_column('contracts', 'payment_schedule')
    op.drop_column('contracts', 'offer_id')
    op.drop_column('contracts', 'renewal_notice_days')
    op.drop_column('contracts', 'contract_metadata')
    op.drop_column('contracts', 'signed_by')
    op.drop_column('contracts', 'terms_and_conditions')
    op.drop_column('contracts', 'sla_terms')
    op.alter_column('negotiation_sessions', 'total_messages',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('negotiation_sessions_session_id_key'), 'negotiation_sessions', type_='unique')
    op.drop_index(op.f('ix_negotiation_sessions_session_id'), table_name='negotiation_sessions')
    op.create_index(op.f('ix_negotiation_sessions_session_id'), 'negotiation_sessions', ['session_id'], unique=True)
    op.create_unique_constraint('uq_negotiation_request_vendor', 'negotiation_sessions', ['request_id', 'vendor_id'])
    op.alter_column('offers', 'payment_terms',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(op.f('offers_offer_id_key'), 'offers', type_='unique')
    op.drop_index(op.f('ix_offers_offer_id'), table_name='offers')
    op.create_index(op.f('ix_offers_offer_id'), 'offers', ['offer_id'], unique=True)
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_constraint(op.f('organizations_organization_id_key'), 'organizations', type_='unique')
    op.drop_index(op.f('ix_organizations_organization_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_organization_id'), 'organizations', ['organization_id'], unique=True)
    op.drop_column('organizations', 'deleted_at')
    op.add_column('policy_configs', sa.Column('policy_name', sa.String(length=100), nullable=False))
    op.add_column('policy_configs', sa.Column('policy_data', sa.JSON(), nullable=False))
    op.add_column('policy_configs', sa.Column('version', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_policy_configs_policy_id'), table_name='policy_configs')
    op.drop_constraint(op.f('policy_configs_policy_id_key'), 'policy_configs', type_='unique')
    op.create_index(op.f('ix_policy_configs_policy_name'), 'policy_configs', ['policy_name'], unique=False)
    op.create_index(op.f('ix_policy_configs_policy_type'), 'policy_configs', ['policy_type'], unique=False)
    op.create_unique_constraint('uq_policy_org_version', 'policy_configs', ['policy_name', 'organization_id', 'version'])
    op.drop_column('policy_configs', 'priority')
    op.drop_column('policy_configs', 'rules')
    op.drop_column('policy_configs', 'name')
    op.drop_column('policy_configs', 'policy_id')
    op.drop_constraint(op.f('requests_request_id_key'), 'requests', type_='unique')
    op.drop_index(op.f('ix_requests_request_id'), table_name='requests')
    op.create_index(op.f('ix_requests_request_id'), 'requests', ['request_id'], unique=True)
    op.drop_constraint(op.f('user_accounts_email_key'), 'user_accounts', type_='unique')
    op.drop_constraint(op.f('user_accounts_username_key'), 'user_accounts', type_='unique')
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=True)
    op.drop_index(op.f('ix_user_accounts_username'), table_name='user_accounts')
    op.create_index(op.f('ix_user_accounts_username'), 'user_accounts', ['username'], unique=True)
    op.drop_constraint(op.f('user_sessions_session_id_key'), 'user_sessions', type_='unique')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.drop_constraint(op.f('vendor_profiles_vendor_id_key'), 'vendor_profiles', type_='unique')
    op.drop_index(op.f('ix_vendor_profiles_vendor_id'), table_name='vendor_profiles')
    op.create_index(op.f('ix_vendor_profiles_vendor_id'), 'vendor_profiles', ['vendor_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_profiles_vendor_id'), table_name='vendor_profiles')
    op.create_index(op.f('ix_vendor_profiles_vendor_id'), 'vendor_profiles', ['vendor_id'], unique=False)
    op.create_unique_constraint(op.f('vendor_profiles_vendor_id_key'), 'vendor_profiles', ['vendor_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=False)
    op.create_unique_constraint(op.f('user_sessions_session_id_key'), 'user_sessions', ['session_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_accounts_username'), table_name='user_accounts')
    op.create_index(op.f('ix_user_accounts_username'), 'user_accounts', ['username'], unique=False)
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=False)
    op.create_unique_constraint(op.f('user_accounts_username_key'), 'user_accounts', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_accounts_email_key'), 'user_accounts', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_requests_request_id'), table_name='requests')
    op.create_index(op.f('ix_requests_request_id'), 'requests', ['request_id'], unique=False)
    op.create_unique_constraint(op.f('requests_request_id_key'), 'requests', ['request_id'], postgresql_nulls_not_distinct=False)
    op.add_column('policy_configs', sa.Column('policy_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('policy_configs', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('policy_configs', sa.Column('rules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('policy_configs', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_policy_org_version', 'policy_configs', type_='unique')
    op.drop_index(op.f('ix_policy_configs_policy_type'), table_name='policy_configs')
    op.drop_index(op.f('ix_policy_configs_policy_name'), table_name='policy_configs')
    op.create_unique_constraint(op.f('policy_configs_policy_id_key'), 'policy_configs', ['policy_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_policy_configs_policy_id'), 'policy_configs', ['policy_id'], unique=False)
    op.drop_column('policy_configs', 'version')
    op.drop_column('policy_configs', 'policy_data')
    op.drop_column('policy_configs', 'policy_name')
    op.add_column('organizations', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_organizations_organization_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_organization_id'), 'organizations', ['organization_id'], unique=False)
    op.create_unique_constraint(op.f('organizations_organization_id_key'), 'organizations', ['organization_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.drop_index(op.f('ix_offers_offer_id'), table_name='offers')
    op.create_index(op.f('ix_offers_offer_id'), 'offers', ['offer_id'], unique=False)
    op.create_unique_constraint(op.f('offers_offer_id_key'), 'offers', ['offer_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('offers', 'payment_terms',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('uq_negotiation_request_vendor', 'negotiation_sessions', type_='unique')
    op.drop_index(op.f('ix_negotiation_sessions_session_id'), table_name='negotiation_sessions')
    op.create_index(op.f('ix_negotiation_sessions_session_id'), 'negotiation_sessions', ['session_id'], unique=False)
    op.create_unique_constraint(op.f('negotiation_sessions_session_id_key'), 'negotiation_sessions', ['session_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('negotiation_sessions', 'total_messages',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.add_column('contracts', sa.Column('sla_terms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('terms_and_conditions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('signed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('contract_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('renewal_notice_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('offer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('payment_schedule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key(op.f('contracts_signed_by_fkey'), 'contracts', 'user_accounts', ['signed_by'], ['id'])
    op.create_foreign_key(op.f('contracts_offer_id_fkey'), 'contracts', 'offers', ['offer_id'], ['id'])
    op.drop_index(op.f('ix_contracts_contract_id'), table_name='contracts')
    op.create_index(op.f('ix_contracts_contract_id'), 'contracts', ['contract_id'], unique=False)
    op.create_unique_constraint(op.f('contracts_contract_id_key'), 'contracts', ['contract_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('contracts', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contracts', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('contracts', 'special_terms')
    op.drop_column('contracts', 'value_adds')
    op.drop_column('contracts', 'erp_synced_at')
    op.drop_column('contracts', 'erp_sync_status')
    op.drop_column('contracts', 'purchase_order_id')
    op.drop_column('contracts', 'docusign_envelope_id')
    op.drop_column('contracts', 'vendor_signature_date')
    op.drop_column('contracts', 'buyer_signature_date')
    op.drop_column('contracts', 'signed_by_vendor')
    op.drop_column('contracts', 'signed_by_buyer')
    op.drop_column('contracts', 'template_version')
    op.drop_column('contracts', 'document_hash')
    op.drop_column('contracts', 'renewal_date')
    op.drop_column('contracts', 'payment_terms')
    op.drop_column('contracts', 'term_months')
    op.drop_column('contracts', 'quantity')
    op.drop_column('contracts', 'unit_price')
    op.drop_column('contracts', 'final_offer_id')
    op.add_column('audit_logs', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('log_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('log_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=False)
    op.create_unique_constraint(op.f('audit_logs_log_id_key'), 'audit_logs', ['log_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('audit_logs', 'event_data')
    op.drop_column('audit_logs', 'negotiation_session_id')
    op.drop_column('audit_logs', 'actor_id')
    op.drop_column('audit_logs', 'actor_type')
    op.add_column('api_keys', sa.Column('key_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_api_keys_key_id'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_id'), 'api_keys', ['key_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_unique_constraint(op.f('api_keys_key_id_key'), 'api_keys', ['key_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('api_keys', 'usage_count')
    op.drop_column('api_keys', 'hashed_secret')
    op.drop_table('password_history')
    op.drop_index(op.f('ix_oauth_connections_provider'), table_name='oauth_connections')
    op.drop_table('oauth_connections')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_negotiation_events_session_id'), table_name='negotiation_events')
    op.drop_table('negotiation_events')
    # ### end Alembic commands ###
